// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: medal-service/medal.proto

package medals

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRankingByCountryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit string `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetRankingByCountryRequest) Reset() {
	*x = GetRankingByCountryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankingByCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingByCountryRequest) ProtoMessage() {}

func (x *GetRankingByCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingByCountryRequest.ProtoReflect.Descriptor instead.
func (*GetRankingByCountryRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{0}
}

func (x *GetRankingByCountryRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type RankingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	GoldCount   int32  `protobuf:"varint,1,opt,name=gold_count,json=goldCount,proto3" json:"gold_count,omitempty"`
	SilverCount int32  `protobuf:"varint,2,opt,name=silver_count,json=silverCount,proto3" json:"silver_count,omitempty"`
	BronzeCount int32  `protobuf:"varint,3,opt,name=bronze_count,json=bronzeCount,proto3" json:"bronze_count,omitempty"`
	TotalCount  int32  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *RankingResponse) Reset() {
	*x = RankingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingResponse) ProtoMessage() {}

func (x *RankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingResponse.ProtoReflect.Descriptor instead.
func (*RankingResponse) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{1}
}

func (x *RankingResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RankingResponse) GetGoldCount() int32 {
	if x != nil {
		return x.GoldCount
	}
	return 0
}

func (x *RankingResponse) GetSilverCount() int32 {
	if x != nil {
		return x.SilverCount
	}
	return 0
}

func (x *RankingResponse) GetBronzeCount() int32 {
	if x != nil {
		return x.BronzeCount
	}
	return 0
}

func (x *RankingResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetRankingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rankings []*RankingResponse `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`
}

func (x *GetRankingResponse) Reset() {
	*x = GetRankingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingResponse) ProtoMessage() {}

func (x *GetRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingResponse.ProtoReflect.Descriptor instead.
func (*GetRankingResponse) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{2}
}

func (x *GetRankingResponse) GetRankings() []*RankingResponse {
	if x != nil {
		return x.Rankings
	}
	return nil
}

type Medal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AthleteId   string               `protobuf:"bytes,4,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Country     string               `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	CreatedAt   *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Medal) Reset() {
	*x = Medal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Medal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Medal) ProtoMessage() {}

func (x *Medal) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Medal.ProtoReflect.Descriptor instead.
func (*Medal) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{3}
}

func (x *Medal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Medal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Medal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Medal) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *Medal) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Medal) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Medal) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMedalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AthleteId   string `protobuf:"bytes,3,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Country     string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *CreateMedalRequest) Reset() {
	*x = CreateMedalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedalRequest) ProtoMessage() {}

func (x *CreateMedalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedalRequest.ProtoReflect.Descriptor instead.
func (*CreateMedalRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMedalRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateMedalRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMedalRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *CreateMedalRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetMedalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit      int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortOrder  string `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	TypeFilter string `protobuf:"bytes,5,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
}

func (x *GetMedalsRequest) Reset() {
	*x = GetMedalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsRequest) ProtoMessage() {}

func (x *GetMedalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsRequest.ProtoReflect.Descriptor instead.
func (*GetMedalsRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{5}
}

func (x *GetMedalsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMedalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMedalsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *GetMedalsRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

type GetMedalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medals []*Medal `protobuf:"bytes,1,rep,name=medals,proto3" json:"medals,omitempty"`
}

func (x *GetMedalsResponse) Reset() {
	*x = GetMedalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsResponse) ProtoMessage() {}

func (x *GetMedalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsResponse.ProtoReflect.Descriptor instead.
func (*GetMedalsResponse) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{6}
}

func (x *GetMedalsResponse) GetMedals() []*Medal {
	if x != nil {
		return x.Medals
	}
	return nil
}

type GetMedalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMedalRequest) Reset() {
	*x = GetMedalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalRequest) ProtoMessage() {}

func (x *GetMedalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalRequest.ProtoReflect.Descriptor instead.
func (*GetMedalRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{7}
}

func (x *GetMedalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMedalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medal *Medal `protobuf:"bytes,1,opt,name=medal,proto3" json:"medal,omitempty"`
}

func (x *GetMedalResponse) Reset() {
	*x = GetMedalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalResponse) ProtoMessage() {}

func (x *GetMedalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalResponse.ProtoReflect.Descriptor instead.
func (*GetMedalResponse) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{8}
}

func (x *GetMedalResponse) GetMedal() *Medal {
	if x != nil {
		return x.Medal
	}
	return nil
}

type GetMedalsByCountryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit   int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *GetMedalsByCountryRequest) Reset() {
	*x = GetMedalsByCountryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalsByCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsByCountryRequest) ProtoMessage() {}

func (x *GetMedalsByCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsByCountryRequest.ProtoReflect.Descriptor instead.
func (*GetMedalsByCountryRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{9}
}

func (x *GetMedalsByCountryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMedalsByCountryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMedalsByCountryRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetMedalsByCountryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medals []*Medal `protobuf:"bytes,1,rep,name=medals,proto3" json:"medals,omitempty"`
}

func (x *GetMedalsByCountryResponse) Reset() {
	*x = GetMedalsByCountryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalsByCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsByCountryResponse) ProtoMessage() {}

func (x *GetMedalsByCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsByCountryResponse.ProtoReflect.Descriptor instead.
func (*GetMedalsByCountryResponse) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{10}
}

func (x *GetMedalsByCountryResponse) GetMedals() []*Medal {
	if x != nil {
		return x.Medals
	}
	return nil
}

type UpdateMedalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AthleteId   string `protobuf:"bytes,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Country     string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *UpdateMedalRequest) Reset() {
	*x = UpdateMedalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedalRequest) ProtoMessage() {}

func (x *UpdateMedalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedalRequest.ProtoReflect.Descriptor instead.
func (*UpdateMedalRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMedalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMedalRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMedalRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateMedalRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMedalRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *UpdateMedalRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type UpdateMedalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medal *Medal `protobuf:"bytes,1,opt,name=medal,proto3" json:"medal,omitempty"`
}

func (x *UpdateMedalResponse) Reset() {
	*x = UpdateMedalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedalResponse) ProtoMessage() {}

func (x *UpdateMedalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedalResponse.ProtoReflect.Descriptor instead.
func (*UpdateMedalResponse) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMedalResponse) GetMedal() *Medal {
	if x != nil {
		return x.Medal
	}
	return nil
}

type DeleteMedalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMedalRequest) Reset() {
	*x = DeleteMedalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedalRequest) ProtoMessage() {}

func (x *DeleteMedalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedalRequest.ProtoReflect.Descriptor instead.
func (*DeleteMedalRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMedalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMedalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteMedalResponse) Reset() {
	*x = DeleteMedalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedalResponse) ProtoMessage() {}

func (x *DeleteMedalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedalResponse.ProtoReflect.Descriptor instead.
func (*DeleteMedalResponse) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteMedalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMedalsByAthleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AthleteId string `protobuf:"bytes,1,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
}

func (x *GetMedalsByAthleteRequest) Reset() {
	*x = GetMedalsByAthleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalsByAthleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsByAthleteRequest) ProtoMessage() {}

func (x *GetMedalsByAthleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsByAthleteRequest.ProtoReflect.Descriptor instead.
func (*GetMedalsByAthleteRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{15}
}

func (x *GetMedalsByAthleteRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

type GetMedalsByTimeRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Page      int32                `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit     int32                `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetMedalsByTimeRangeRequest) Reset() {
	*x = GetMedalsByTimeRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_service_medal_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalsByTimeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsByTimeRangeRequest) ProtoMessage() {}

func (x *GetMedalsByTimeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medal_service_medal_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsByTimeRangeRequest.ProtoReflect.Descriptor instead.
func (*GetMedalsByTimeRangeRequest) Descriptor() ([]byte, []int) {
	return file_medal_service_medal_proto_rawDescGZIP(), []int{16}
}

func (x *GetMedalsByTimeRangeRequest) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMedalsByTimeRangeRequest) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetMedalsByTimeRangeRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMedalsByTimeRangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_medal_service_medal_proto protoreflect.FileDescriptor

var file_medal_service_medal_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x65, 0x64,
	0x61, 0x6c, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x67, 0x6f, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x69, 0x6c, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x69, 0x6c, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x72, 0x6f, 0x6e, 0x7a, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x72, 0x6f, 0x6e, 0x7a, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x48, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x72,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0xfc, 0x01, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x83,
	0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x22, 0x7c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x22, 0x39, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6d, 0x65, 0x64, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x22, 0x21, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x22, 0x5f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x42, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6d, 0x65, 0x64, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x22, 0xa9, 0x01,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x05, 0x6d,
	0x65, 0x64, 0x61, 0x6c, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x3a, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c,
	0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74,
	0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x32, 0x9b, 0x05, 0x0a, 0x0c, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x64, 0x61, 0x6c, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c,
	0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x3b, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x16, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x19,
	0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x64, 0x61,
	0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x20, 0x2e, 0x6d, 0x65,
	0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x64, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x20, 0x2e,
	0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x42,
	0x79, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x22, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x61, 0x6c, 0x73, 0x42, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x50, 0x0a, 0x10, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_medal_service_medal_proto_rawDescOnce sync.Once
	file_medal_service_medal_proto_rawDescData = file_medal_service_medal_proto_rawDesc
)

func file_medal_service_medal_proto_rawDescGZIP() []byte {
	file_medal_service_medal_proto_rawDescOnce.Do(func() {
		file_medal_service_medal_proto_rawDescData = protoimpl.X.CompressGZIP(file_medal_service_medal_proto_rawDescData)
	})
	return file_medal_service_medal_proto_rawDescData
}

var file_medal_service_medal_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_medal_service_medal_proto_goTypes = []interface{}{
	(*GetRankingByCountryRequest)(nil),  // 0: medal.GetRankingByCountryRequest
	(*RankingResponse)(nil),             // 1: medal.RankingResponse
	(*GetRankingResponse)(nil),          // 2: medal.GetRankingResponse
	(*Medal)(nil),                       // 3: medal.Medal
	(*CreateMedalRequest)(nil),          // 4: medal.CreateMedalRequest
	(*GetMedalsRequest)(nil),            // 5: medal.GetMedalsRequest
	(*GetMedalsResponse)(nil),           // 6: medal.GetMedalsResponse
	(*GetMedalRequest)(nil),             // 7: medal.GetMedalRequest
	(*GetMedalResponse)(nil),            // 8: medal.GetMedalResponse
	(*GetMedalsByCountryRequest)(nil),   // 9: medal.GetMedalsByCountryRequest
	(*GetMedalsByCountryResponse)(nil),  // 10: medal.GetMedalsByCountryResponse
	(*UpdateMedalRequest)(nil),          // 11: medal.UpdateMedalRequest
	(*UpdateMedalResponse)(nil),         // 12: medal.UpdateMedalResponse
	(*DeleteMedalRequest)(nil),          // 13: medal.DeleteMedalRequest
	(*DeleteMedalResponse)(nil),         // 14: medal.DeleteMedalResponse
	(*GetMedalsByAthleteRequest)(nil),   // 15: medal.GetMedalsByAthleteRequest
	(*GetMedalsByTimeRangeRequest)(nil), // 16: medal.GetMedalsByTimeRangeRequest
	(*timestamp.Timestamp)(nil),         // 17: google.protobuf.Timestamp
}
var file_medal_service_medal_proto_depIdxs = []int32{
	1,  // 0: medal.GetRankingResponse.rankings:type_name -> medal.RankingResponse
	17, // 1: medal.Medal.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: medal.Medal.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 3: medal.GetMedalsResponse.medals:type_name -> medal.Medal
	3,  // 4: medal.GetMedalResponse.medal:type_name -> medal.Medal
	3,  // 5: medal.GetMedalsByCountryResponse.medals:type_name -> medal.Medal
	3,  // 6: medal.UpdateMedalResponse.medal:type_name -> medal.Medal
	17, // 7: medal.GetMedalsByTimeRangeRequest.start_time:type_name -> google.protobuf.Timestamp
	17, // 8: medal.GetMedalsByTimeRangeRequest.end_time:type_name -> google.protobuf.Timestamp
	4,  // 9: medal.MedalService.CreateMedal:input_type -> medal.CreateMedalRequest
	7,  // 10: medal.MedalService.GetMedal:input_type -> medal.GetMedalRequest
	5,  // 11: medal.MedalService.GetMedals:input_type -> medal.GetMedalsRequest
	11, // 12: medal.MedalService.UpdateMedal:input_type -> medal.UpdateMedalRequest
	13, // 13: medal.MedalService.DeleteMedal:input_type -> medal.DeleteMedalRequest
	9,  // 14: medal.MedalService.GetMedalsByCountry:input_type -> medal.GetMedalsByCountryRequest
	15, // 15: medal.MedalService.GetMedalsByAthlete:input_type -> medal.GetMedalsByAthleteRequest
	16, // 16: medal.MedalService.GetMedalsByTimeRange:input_type -> medal.GetMedalsByTimeRangeRequest
	0,  // 17: medal.MedalService.RankingByCountry:input_type -> medal.GetRankingByCountryRequest
	3,  // 18: medal.MedalService.CreateMedal:output_type -> medal.Medal
	8,  // 19: medal.MedalService.GetMedal:output_type -> medal.GetMedalResponse
	6,  // 20: medal.MedalService.GetMedals:output_type -> medal.GetMedalsResponse
	12, // 21: medal.MedalService.UpdateMedal:output_type -> medal.UpdateMedalResponse
	14, // 22: medal.MedalService.DeleteMedal:output_type -> medal.DeleteMedalResponse
	6,  // 23: medal.MedalService.GetMedalsByCountry:output_type -> medal.GetMedalsResponse
	6,  // 24: medal.MedalService.GetMedalsByAthlete:output_type -> medal.GetMedalsResponse
	6,  // 25: medal.MedalService.GetMedalsByTimeRange:output_type -> medal.GetMedalsResponse
	2,  // 26: medal.MedalService.RankingByCountry:output_type -> medal.GetRankingResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_medal_service_medal_proto_init() }
func file_medal_service_medal_proto_init() {
	if File_medal_service_medal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_medal_service_medal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankingByCountryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Medal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMedalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalsByCountryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalsByCountryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMedalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMedalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMedalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMedalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalsByAthleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_service_medal_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalsByTimeRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_medal_service_medal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medal_service_medal_proto_goTypes,
		DependencyIndexes: file_medal_service_medal_proto_depIdxs,
		MessageInfos:      file_medal_service_medal_proto_msgTypes,
	}.Build()
	File_medal_service_medal_proto = out.File
	file_medal_service_medal_proto_rawDesc = nil
	file_medal_service_medal_proto_goTypes = nil
	file_medal_service_medal_proto_depIdxs = nil
}
